apiVersion: v1
kind: Pod
metadata:
  name: test-grpc-client
  namespace: grpc-test
spec:
  serviceAccountName: endpoints-reader
  containers:
    - name: test-grpc-client
      image: zcong/k8s-grpc:latest
      imagePullPolicy: Always
      command:
        - node
        - ./dist/example/client.js
      env:
        - name: SERVICE_NAME
          value: test-grpc-server
        - name: SERVICE_NS
          value: grpc-test
        - name: SERVICE_PORT
          value: '8080'
