---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-grpc-server
  namespace: grpc-test
spec:
  selector:
    matchLabels:
      app: test-grpc-server
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: test-grpc-server
    spec:
      containers:
        - name: test-grpc-server
          image: zcong/k8s-grpc:latest
          # imagePullPolicy: Always
          ports:
            - containerPort: 8080
          command:
            - node
            - ./dist/example/server.js
---
apiVersion: v1
kind: Service
metadata:
  name: test-grpc-server
  namespace: grpc-test
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: test-grpc-server
  type: ClusterIP
